default: &default
 adapter: postgresql
 encoding: unicode
 host: localhost
 pool: 5
 username: username
 password: password

development:
 <<: *default
 database: app_development

test:
 <<: *default
 database: app_test

production:
 <<: *default
 database: app_production