default: &default
 adapter: postgresql
 encoding: unicode
 host: localhost
 pool: 5
 username: nami_admin
 password: 1234
 host: localhost
 port: 5432
 
development:
 <<: *default
 database: namidb

test:
 <<: *default
 database: app_test

production:
 <<: *default
 database: app_production
